### ISSUE TITLE
View saved goal Chart

### ISSUE THREAD

**Issue by dinaolmelak** [Dollar-Dynasty/finance-app#49]
# Feature Request

## Description
Display the Saving Goals chart in the Dashboard.

## User Story
As a [user], I want [view my saved goals in the dashboard] so that [I can examine my expenses].

## Acceptance Criteria
- Able to see the chart for saving goals in the `Dashboard`

## Technical Considerations (Optional)
[plotly](https://plotly.com/) would come in handy 
- This ticket is also related to #47 

## Design Mockups (Optional)
- Look at the Saving Goals section on the following picture.
![IMG_1902 (1)](https://github.com/Dollar-Dynasty/finance-app/assets/32272045/0fa3c3f1-cc19-49ed-9fa1-18b992affc7b)

## Implementation Steps (Optional)
1. [List high-level steps or tasks to implement this feature. This can be updated as more details are determined.]

## Testing Plan
Manual testing to see if the data along with the chart is there.

## Definition of Done
- [x] Code is written and reviewed.
- [x] Done Before Deadline
- [x] Feature meets acceptance criteria.

## Additional Information (Optional)
- There is no way for adding goal saving information into DB until #57 is completed. Nevertheless, for the sake of this ticket follow the `goalModel` under `models` to manually create the information on your MongoDB.

---

# Checklist
- [x] Feature Requested
- [x] Acceptance Criteria Defined
- [ ] Optional: Technical Considerations Discussed
- [ ] Optional: Design Mockups Attached
- [ ] Optional: Implementation Steps Outlined
- [x] Testing Plan Defined
- [x] Definition of Done Established
- [x] Optional: Additional Information Provided
