### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by dinaolmelak** [Dollar-Dynasty/finance-app#50]
# Feature Request

## Description
A basic Landing page for the web application. As displayed in the picture in the `Design Mockups` the landing page is the start of the web app.

## User Story
As a [user], I want [navigate to either Log In or Register] so that [I could log In or Register].

## Acceptance Criteria
- Basic Landing page, with `Login` and `Register` buttons available. 
- The buttons navigate to the appropriate page

## Technical Considerations (Optional)
- HTML could be used initially but also consider changing the html into `ejs` file

## Design Mockups (Optional)
<img width="455" alt="Screenshot 2024-02-07 at 5 00 55 in the afternoon" src="https://github.com/Dollar-Dynasty/finance-app/assets/32272045/604761f9-3f05-4eef-88f9-5acdd3275423">

## Implementation Steps (Optional)
- You can use the following approach or directly use ejs file for making the `Landing Page`
1. Design the page with HTML initially
2. Change the HTML into ejs
3. Make sure that the buttons navigate to the appropriate pages

## Testing Plan
- We have the landing page in our `views/pages` directory.
- the landing page is an ejs file
- The buttons work

## Definition of Done
- [x] Code is written and reviewed.
- [x] Done Before Deadline
- [x] Feature meets acceptance criteria.

## Additional Information (Optional)
- Feel free to use tools out there to convert the HTML file you create into ejs if need be

---

# Checklist
- [x] Feature Requested
- [x] Acceptance Criteria Defined
- [x] Optional: Technical Considerations Discussed
- [x] Optional: Design Mockups Attached
- [x] Optional: Implementation Steps Outlined
- [x] Testing Plan Defined
- [x] Definition of Done Established
- [x] Optional: Additional Information Provided
