### ISSUE TITLE
New User Flow

### ISSUE THREAD

**Issue by dinaolmelak** [Dollar-Dynasty/finance-app#59]
# Feature Request

## Description
We want to have new users directed to the budget creation and goal saving page so that we could gather those information in the MongoDB.

## User Story
As a [user and developer], I want [to create budget and add my goal saving when I create my account] so that [I can see the stats when I get to the Dashboard].

## Acceptance Criteria
- After creating new account, I am redirected to the budget creation and then to goal saving.
- The budget information and goal saving information is saved in the DB

## Technical Considerations (Optional)
N/A

## Design Mockups (Optional)
![Screenshot 2024-02-09 at 1 40 40 in the afternoon](https://github.com/Dollar-Dynasty/finance-app/assets/32272045/a90e8ca3-4f71-424c-bd81-b66e3f3bb878)

## Implementation Steps (Optional)
N/A

## Testing Plan
When creating an account, I am redirected to budget, and then goal saving. I am also able to see that information in the DB

## Definition of Done
- [x] Code is written and reviewed.
- [x] Done Before Deadline
- [x] Feature meets acceptance criteria.

## Additional Information (Optional)
- Consider completing #57 and #60 before this ticket. Nevertheless, it is ok to work on this ticket without completing those two.

---

# Checklist
- [x] Feature Requested
- [x] Acceptance Criteria Defined
- [ ] Optional: Technical Considerations Discussed
- [x] Optional: Design Mockups Attached
- [ ] Optional: Implementation Steps Outlined
- [x] Testing Plan Defined
- [x] Definition of Done Established
- [ ] Optional: Additional Information Provided
